### ISSUE TITLE
dive clean does not work as kurtosis clean -a

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#56]
❯ dive clean
INFO[2023-07-24 11:35:05] Successfully connected to kurtosis engine...
INFO[2023-07-24 11:35:05] Initializing cleaning process...
ERRO[2023-07-24 11:35:21] Failed cleaning with error: An error occurred when trying to perform a clean with the clean-all arg set to 'true'
 --- at /Users/soul/go/pkg/mod/github.com/kurtosis-tech/kurtosis/api/golang@v0.80.8/engine/lib/kurtosis_context/kurtosis_context.go:226 (KurtosisContext.Clean) ---
Caused by: rpc error: code = Unknown desc = An error occurred while cleaning enclaves
 --- at /home/circleci/project/engine/server/engine/server/engine_server_service.go:123 (EngineServerService.Clean) ---
Caused by: Following errors occurred while removing some enclaves :
>>>>>>>>>>>>>>>>> ERROR 0 <<<<<<<<<<<<<<<<<
One or more errors occurred removing the containers in enclave '9456d3b9f4454d10abc73bd914a3ec14':
An error occurred removing enclave container with ID '1b634259a630757e6f44393bd5c3cc855921f0dcaa3a2d2fefda817c1866aed9'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/docker_kurtosis_backend_enclave_functions.go:530 (destroyContainersInEnclaves.func1) ---
Caused by: An error occurred removing container with ID '1b634259a630757e6f44393bd5c3cc855921f0dcaa3a2d2fefda817c1866aed9'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:776 (DockerManager.RemoveContainer) ---
Caused by: Error response from daemon: Could not kill running container 1b634259a630757e6f44393bd5c3cc855921f0dcaa3a2d2fefda817c1866aed9, cannot remove - container 1b634259a630 PID 44068 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes

An error occurred removing enclave container with ID 'e0000dc3968e6b45044f0bd81f99651064254bd5fc726ebe88c22dacc95dc053'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/docker_kurtosis_backend_enclave_functions.go:530 (destroyContainersInEnclaves.func1) ---
Caused by: An error occurred removing container with ID 'e0000dc3968e6b45044f0bd81f99651064254bd5fc726ebe88c22dacc95dc053'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:776 (DockerManager.RemoveContainer) ---
Caused by: Error response from daemon: Could not kill running container e0000dc3968e6b45044f0bd81f99651064254bd5fc726ebe88c22dacc95dc053, cannot remove - container e0000dc3968e PID 43480 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes

An error occurred removing enclave container with ID '691f3ea6c029093118662dbe1e02c255b4a0c4f7ed530a0edaaea543fd18a983'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/docker_kurtosis_backend_enclave_functions.go:530 (destroyContainersInEnclaves.func1) ---
Caused by: An error occurred removing container with ID '691f3ea6c029093118662dbe1e02c255b4a0c4f7ed530a0edaaea543fd18a983'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:776 (DockerManager.RemoveContainer) ---
Caused by: Error response from daemon: Could not kill running container 691f3ea6c029093118662dbe1e02c255b4a0c4f7ed530a0edaaea543fd18a983, cannot remove - container 691f3ea6c029 PID 47511 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes

An error occurred removing enclave container with ID 'd21e16ff14ba5a1d041ceb2a096a8fd9cca01547784a0cd3135e0acedeac420f'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/docker_kurtosis_backend_enclave_functions.go:530 (destroyContainersInEnclaves.func1) ---
Caused by: An error occurred removing container with ID 'd21e16ff14ba5a1d041ceb2a096a8fd9cca01547784a0cd3135e0acedeac420f'
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:776 (DockerManager.RemoveContainer) ---
Caused by: Error response from daemon: Could not kill running container d21e16ff14ba5a1d041ceb2a096a8fd9cca01547784a0cd3135e0acedeac420f, cannot remove - container d21e16ff14ba PID 47856 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes
 --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/docker_kurtosis_backend_enclave_functions.go:566 (destroyContainersInEnclaves) ---
 --- at /home/circleci/project/engine/server/engine/enclave_manager/enclave_manager.go:282 (EnclaveManager.Clean) ---
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hugobyte/dive/common.(*DiveContext).Clean(0x140002880f0)
	/Users/soul/Garage/HugoByte/DIVE/cli/common/types.go:207 +0x170
github.com/hugobyte/dive/commands/clean.NewCleanCmd.func1(0x140002bf800?, {0x100fd6230?, 0x0, 0x0?})
	/Users/soul/Garage/HugoByte/DIVE/cli/commands/clean/clean.go:38 +0x190
github.com/spf13/cobra.(*Command).execute(0x140002bf800, {0x100fd6230, 0x0, 0x0})
	/Users/soul/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x100f94c60)
	/Users/soul/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/soul/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/hugobyte/dive/commands.Execute()
	/Users/soul/Garage/HugoByte/DIVE/cli/commands/root.go:37 +0x24
main.main()
	/Users/soul/Garage/HugoByte/DIVE/cli/main.go:18 +0x60

❯ kurtosis clean -a
INFO[2023-07-24T11:35:51-04:00] Cleaning old Kurtosis engine containers...
INFO[2023-07-24T11:35:51-04:00] Successfully cleaned old Kurtosis engine containers
INFO[2023-07-24T11:35:51-04:00] Cleaning enclaves...
INFO[2023-07-24T11:36:23-04:00] Successfully removed the following enclaves:
9456d3b9f4454d10abc73bd914a3ec14	dive
INFO[2023-07-24T11:36:23-04:00] Successfully cleaned enclaves

**Comment by CyrusVorwald** [comment]
closing because i have not had this error come up again and it seems to have been resolved by https://github.com/kurtosis-tech/kurtosis/issues/959
